apiVersion: v2
name: qbittorrent-vpn
description: qBittorrent with Gluetun VPN sidecar
type: application
version: "0.2.0"
appVersion: "5.1.4"
icon: https://raw.githubusercontent.com/qbittorrent/qBittorrent/master/src/icons/qbittorrent-tray.svg
keywords:
  - torrent
  - bittorrent
home: https://github.com/bdclark/helm-charts/tree/main/charts/qbittorrent-vpn
sources:
  - https://github.com/bdclark/helm-charts/tree/main/charts/qbittorrent-vpn
  - https://github.com/qbittorrent/qBittorrent
  - https://github.com/qdm12/gluetun
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/bdclark/helm-charts/tree/main/charts/qbittorrent-vpn
    - name: qBittorrent
      url: https://www.qbittorrent.org/
    - name: Gluetun
      url: https://github.com/qdm12/gluetun
maintainers:
  - name: bdclark
    email: brian@clark.zone
    url: https://github.com/bdclark
