apiVersion: v2
name: mosquitto
description: Eclipse Mosquitto MQTT broker with authentication and persistence support
type: application
version: 0.5.2
appVersion: 2.0.22
home: https://github.com/bdclark/helm-charts/tree/main/charts/mosquitto
sources:
  - https://github.com/bdclark/helm-charts/tree/main/charts/mosquitto
  - https://github.com/eclipse/mosquitto
icon: https://raw.githubusercontent.com/eclipse/mosquitto/master/logo/mosquitto-logo-min.svg
keywords:
  - mqtt
  - mosquitto
  - eclipse
  - iot
  - broker
  - messaging
  - home-automation
maintainers:
  - name: Brian Clark
    email: brian@clark.zone
    url: https://github.com/bdclark
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/bdclark/helm-charts/tree/main/charts/mosquitto
    - name: Eclipse Mosquitto
      url: https://mosquitto.org/
  artifacthub.io/images: |
    - name: mosquitto
      image: eclipse-mosquitto
