{{- if and .Values.gluetun.enabled .Values.gluetun.controlServer.enabled (not .Values.gluetun.controlServer.existingSecret.name) .Values.gluetun.controlServer.config }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qbittorrent-vpn.fullname" . }}-gluetun-control-auth
  labels:
    {{- include "qbittorrent-vpn.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.gluetun.controlServer.fileName }}: |
    {{- .Values.gluetun.controlServer.config | nindent 4 }}
{{- end }}
