{{- if and .Values.qbittorrent.persistence.config.enabled (not .Values.qbittorrent.persistence.config.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "qbittorrent-vpn.fullname" . }}-config
  labels:
    {{- include "qbittorrent-vpn.labels" . | nindent 4 }}
  {{- with .Values.qbittorrent.persistence.config.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.qbittorrent.persistence.config.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.qbittorrent.persistence.config.size | quote }}
  {{- if .Values.qbittorrent.persistence.config.storageClass }}
  {{- if (eq "-" .Values.qbittorrent.persistence.config.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.qbittorrent.persistence.config.storageClass | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- if and .Values.qbittorrent.persistence.data.enabled (not .Values.qbittorrent.persistence.data.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "qbittorrent-vpn.fullname" . }}-data
  labels:
    {{- include "qbittorrent-vpn.labels" . | nindent 4 }}
  {{- with .Values.qbittorrent.persistence.data.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.qbittorrent.persistence.data.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.qbittorrent.persistence.data.size | quote }}
  {{- if .Values.qbittorrent.persistence.data.storageClass }}
  {{- if (eq "-" .Values.qbittorrent.persistence.data.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.qbittorrent.persistence.data.storageClass | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- if and .Values.gluetun.persistence.enabled (not .Values.gluetun.persistence.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "qbittorrent-vpn.fullname" . }}-gluetun
  labels:
    {{- include "qbittorrent-vpn.labels" . | nindent 4 }}
  {{- with .Values.gluetun.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.gluetun.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.gluetun.persistence.size | quote }}
  {{- if .Values.gluetun.persistence.storageClass }}
  {{- if (eq "-" .Values.gluetun.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.gluetun.persistence.storageClass | quote }}
  {{- end }}
  {{- end }}
{{- end }}
