apiVersion: v1
kind: Service
metadata:
  name: {{ include "qbittorrent-vpn.fullname" . }}
  labels:
    {{- include "qbittorrent-vpn.labels" . | nindent 4 }}
spec:
  type: {{ .Values.qbittorrent.service.type }}
  ports:
    - port: {{ .Values.qbittorrent.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "qbittorrent-vpn.selectorLabels" . | nindent 4 }}
